name = "HeaderArrayFile"
uuid = "e2354eee-dcc0-4139-addc-ce07950641e0"
authors = ["Maros Ivanic"]
version = "1.0.0-DEV"

[deps]
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
